modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Mrbysco/ModJNam-Mod/issues"
license="MIT"

[[mods]]
modId="cactusmod"
version="${file.jarVersion}"
displayName="The Cactus Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-cactus-mod"
logoFile="logo.png"
authors="Mrbysco"
description='''
A ModJam 2018.1 mod.
'''
[[dependencies.cactusmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.cactusmod]]
modId="forge"
mandatory=true
versionRange="[39.0.45,)"
ordering="NONE"
side="BOTH"