modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/ModJNam-Mod/issues"
license="MIT"

[[mods]]
modId="cactusmod"
version="${file.jarVersion}"
displayName="The Cactus Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-cactus-mod"
logoFile="logo.png"
authors="Mrbysco"
description='''
A ModJam 2018.1 mod.
'''
[[dependencies.cactusmod]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.cactusmod]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.131-beta,)"
ordering="NONE"
side="BOTH"